#Onde você guarda a lista de dados

cursos = [
    {"id": 01, 
     "nome":"Python Básico",
     "descrição": "Introdução ao Python",
     "carga": "40h"},
    {"id": 02,
     "nome": "HTML - CSS",
     "descrição": "Do básico ao avançado em HTML e CSS",
     "carga": "60h"},
    {"id": 03,
     "nome": "JS - JavaScript Básico",
     "descrição": "Introdução a JS",
     "carga": "40h"},
    {"id":04,
     "nome": "SQL",
     "descrição": "Do básico ao avançado SQL",
     "carga": "60h"},
    {"id": 05,
     "nome": "Java",
     "descrição": "Do básico ao avançado em Java",
     "carga": "80h"},
    {"id": 06,
     "nome": "PHP básico",
     "descrição": "Introdução a PHP",
     "carga": "40h"},
    {"id": 07,
     "nome":,
     "descrição":,
     "carga":},
    {"id": 08,
     "nome":,
     "descrição":,
     "carga":},
    {"id": 09,
     "nome":,
     "descrição":,
     "carga":},
    {"id": 10,
     "nome":,
     "descrição":,
     "carga":},
]